"""
MatchingEngine implementing price-time priority (FIFO) execution.
Executes incoming market and crossing limit orders, generating Trade events
and directly driving order book state transitions and price formation.
"""

from typing import List, Optional
from market.order import Order, OrderType, Side
from market.order_book import OrderBook
from market.trade import Trade


class MatchingEngine:
    """
    Deterministic matching engine for the Limit Order Book.

    Principles:
    - Pure FIFO queue within each discrete price level.
    - Market orders walk the book level-by-level consuming available liquidity.
    - Crossing limit orders execute against resting depth up to their limit price,
      with any remaining unfilled portion resting on the book.
    - Executed trades update the book's last_trade_price immediately.
    """

    def __init__(self, order_book: OrderBook):
        self.book = order_book
        self.trade_counter = 0
        self.executed_trades: List[Trade] = []

    def _next_trade_id(self) -> int:
        self.trade_counter += 1
        return self.trade_counter

    def submit_order(self, order: Order, timestamp: int = 0) -> List[Trade]:
        """
        Submits an order to the matching engine.
        Returns a list of Trade objects generated by immediate executions.
        """
        order.timestamp = timestamp
        trades: List[Trade] = []

        if order.order_type == OrderType.MARKET:
            trades = self._execute_market_order(order, timestamp)
        elif order.order_type == OrderType.LIMIT:
            trades = self._execute_limit_order(order, timestamp)
        else:
            raise ValueError(f"Unknown order type: {order.order_type}")

        if trades:
            self.executed_trades.extend(trades)
            self.book.last_trade_price = trades[-1].price

        return trades

    def _execute_market_order(self, order: Order, timestamp: int) -> List[Trade]:
        """
        Matches an aggressive market order against the opposing side of the book.
        A market buy consumes asks from lowest to highest.
        A market sell consumes bids from highest to lowest.
        """
        trades: List[Trade] = []

        if order.side == Side.BUY:
            # Consume asks starting from best (lowest) ask
            while order.remaining_quantity > 1e-9 and self.book.asks:
                best_ask_price, level = self.book.asks.peekitem(0)
                level_trades = self._fill_against_level(order, level, Side.BUY, timestamp)
                trades.extend(level_trades)

                if level.is_empty:
                    del self.book.asks[best_ask_price]

        elif order.side == Side.SELL:
            # Consume bids starting from best (highest) bid
            while order.remaining_quantity > 1e-9 and self.book.bids:
                best_bid_price, level = self.book.bids.peekitem(-1)
                level_trades = self._fill_against_level(order, level, Side.SELL, timestamp)
                trades.extend(level_trades)

                if level.is_empty:
                    del self.book.bids[best_bid_price]

        return trades

    def _execute_limit_order(self, order: Order, timestamp: int) -> List[Trade]:
        """
        Processes a limit order:
        - If crossing the spread, matches against resting depth.
        - Any unfilled quantity is added to the book as resting liquidity.
        """
        trades: List[Trade] = []
        order_price = self.book.round(order.price)
        order.price = order_price

        if order.side == Side.BUY:
            # Crossing if price >= best_ask
            while (
                order.remaining_quantity > 1e-9
                and self.book.asks
                and order_price >= self.book.asks.peekitem(0)[0]
            ):
                best_ask_price, level = self.book.asks.peekitem(0)
                level_trades = self._fill_against_level(order, level, Side.BUY, timestamp)
                trades.extend(level_trades)

                if level.is_empty:
                    del self.book.asks[best_ask_price]

            # If remaining quantity exists, rest on the bid side
            if order.remaining_quantity > 1e-9:
                self.book.add_limit_order(order)

        elif order.side == Side.SELL:
            # Crossing if price <= best_bid
            while (
                order.remaining_quantity > 1e-9
                and self.book.bids
                and order_price <= self.book.bids.peekitem(-1)[0]
            ):
                best_bid_price, level = self.book.bids.peekitem(-1)
                level_trades = self._fill_against_level(order, level, Side.SELL, timestamp)
                trades.extend(level_trades)

                if level.is_empty:
                    del self.book.bids[best_bid_price]

            # If remaining quantity exists, rest on the ask side
            if order.remaining_quantity > 1e-9:
                self.book.add_limit_order(order)

        return trades

    def _fill_against_level(
        self,
        taker_order: Order,
        level,
        aggressor_side: Side,
        timestamp: int,
    ) -> List[Trade]:
        """
        Matches an incoming taker order against resting orders in a price level FIFO.
        """
        trades: List[Trade] = []

        while taker_order.remaining_quantity > 1e-9 and level.orders:
            maker_order = level.orders[0]
            fill_qty = min(taker_order.remaining_quantity, maker_order.remaining_quantity)

            if fill_qty <= 1e-9:
                level.orders.popleft()
                self.book.order_map.pop(maker_order.order_id, None)
                continue

            taker_order.fill(fill_qty)
            maker_order.fill(fill_qty)
            level.deduct_quantity(fill_qty)

            trade = Trade(
                trade_id=self._next_trade_id(),
                maker_order_id=maker_order.order_id,
                taker_order_id=taker_order.order_id,
                maker_id=maker_order.trader_id,
                taker_id=taker_order.trader_id,
                side=aggressor_side,
                price=level.price,
                quantity=fill_qty,
                timestamp=timestamp,
            )
            trades.append(trade)

            if maker_order.is_filled:
                level.orders.popleft()
                self.book.order_map.pop(maker_order.order_id, None)

        return trades

    def cancel_order(self, order_id: int) -> Optional[Order]:
        """Cancels a resting order from the order book."""
        return self.book.cancel_order(order_id)

    @property
    def total_trade_volume(self) -> float:
        """Sum of all executed trade volumes."""
        return sum(t.quantity for t in self.executed_trades)

    @property
    def trade_count(self) -> int:
        """Total number of executed trades."""
        return len(self.executed_trades)
